### ISSUE TITLE
Usage as a completion backend

### ISSUE THREAD

**Issue by lilactown** [zerolfx/copilot.el#151]
I use vertico and corfu combined with libraries like consult that provide completing-read implementations for my completion setup right now. What do you think about adding a completing-read implementation and using copilot as a backend for those other completion UIs?

As it stands right now, I have to use different bindings and UIs depending on if I want to use copilot or my preferred completion (xref, LSP, REPL, etc.). My goal is to simplify and unify the amount of UI and bindings I need to juggle in my workflow.

**Comment by zerolfx** [comment]
I've attempted to integrate it as a `company-mode` backend initially, but encountered issues where Copilot frequently generates multi-line completions that are challenging to display alongside other results as a completion candidate. (This means that only part of the completion is visible, and it takes longer than other backends due to network delay.)
