### ISSUE TITLE
suggestion closes when exiting insert-mode in my custom modal editing

### ISSUE THREAD

**Issue by hrehfeld** [zerolfx/copilot.el#54]
I enter insert-mode, write something, copilot suggestion shows, but when I exit insert-mode, the suggestion is gone. Just `copilot-accept-completion` does nothing now.

How can I fix this? What are the triggers for stopping to show the suggestion?

**Comment by zerolfx** [comment]
https://github.com/zerolfx/copilot.el/blob/826995c260cf37b891ca23a4c7f726a3903c2c71/copilot.el#L507-L519

This behavior is by design, which aims to prevent copilot from distracting you when reading code.

If you trigger any non-copilot command, it will clear the suggestion. To keep the suggestions from exiting insert-mode, you can modify the condition to:

```elisp
  (when (and this-command
             (not (s-equals-p this-command #'evil-normal-state))
             (not (and (symbolp this-command)
                       (s-starts-with-p "copilot-" (symbol-name this-command)))))
```
In addition, you can always use `M-x copilot-complete` to manually get a completion.

**Comment by hrehfeld** [comment]
See https://github.com/zerolfx/copilot.el/pull/55
