### ISSUE TITLE
jsonrpc wrong-type-argument on login attempt

### ISSUE THREAD

**Issue by titaniumbones** [zerolfx/copilot.el#70]
**EDIT:** I see there are lots of closed jsonrpc issues in the repo.  I have now tried the following:

- installed node 16.17.1 using fnm and add `(setq copilot-node-executable "/home/matt/.fnm/node-versions/v16.17.1/installation/bin/node")` to my use-package straight declaration (taken from your docs). 
- ensured that jsonrpc is recent (1.0.16)

Hi, I've just installed copilot.el and tried to login.  I get this error when running `copilot-login`: 
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p t)
 jsonrpc--log-event(#<jsonrpc-process-connection jsonrpc-process-connection-157189db4dde> (:jsonrpc "2.0" :id 2 :method "signInInitiate" :params (:dummy "signInInitiate")) client)
  #f(compiled-function (arg1 &rest rest) "Send MESSAGE, a JSON object, to CONNECTION." #<bytecode 0xb90db397f3a5c5c>)(#<jsonrpc-process-connection jsonrpc-process-connection-157189db4dde> :id 2 :method signInInitiate :params (:dummy "signInInitiate"))
  apply(#f(compiled-function (arg1 &rest rest) "Send MESSAGE, a JSON object, to CONNECTION." #<bytecode 0xb90db397f3a5c5c>) #<jsonrpc-process-connection jsonrpc-process-connection-157189db4dde> (:id 2 :method signInInitiate :params (:dummy "signInInitiate")))
  jsonrpc-connection-send(#<jsonrpc-process-connection jsonrpc-process-connection-157189db4dde> :id 2 :method signInInitiate :params (:dummy "signInInitiate"))
  jsonrpc--async-request-1(#<jsonrpc-process-connection jsonrpc-process-connection-157189db4dde> signInInitiate (:dummy "signInInitiate") :success-fn #f(compiled-function (result) #<bytecode -0x1472a295dd498004>) :error-fn #f(compiled-function (jsonrpc-lambda-elem0) #<bytecode -0x2751616efa8f26e>) :timeout-fn #f(compiled-function () #<bytecode -0x1fea87a1b1ab2058>))
  apply(jsonrpc--async-request-1 #<jsonrpc-process-connection jsonrpc-process-connection-157189db4dde> signInInitiate (:dummy "signInInitiate") :success-fn #f(compiled-function (result) #<bytecode -0x1472a295dd498004>) :error-fn #f(compiled-function (jsonrpc-lambda-elem0) #<bytecode -0x2751616efa8f26e>) :timeout-fn #f(compiled-function () #<bytecode -0x1fea87a1b1ab2058>) nil)
  jsonrpc-request(#<jsonrpc-process-connection jsonrpc-process-connection-157189db4dde> signInInitiate (:dummy "signInInitiate"))
  copilot-login()
  funcall-interactively(copilot-login)
 ```
This is on a pretty recent emacs git.  Any idea where I should start looking for issues? I see someone else had a similar but non-identical issue a few months ago in #42 . 

Thanks!

**Comment by dbian** [comment]
![image](https://user-images.githubusercontent.com/1283828/210129604-a876419b-3150-459d-abaa-1c3fa84e87a1.png)

I got this jsrpc error, and I use tramp on win11.

**Comment by zerolfx** [comment]
@dbian This is a separate problem, so please open a new issue.

**Comment by titaniumbones** [comment]
any hints on how to debug this? would love to figure out the issue.

**Comment by zerolfx** [comment]
Could you try Emacs28 to see whether the same problem exists or not?

It looks like that jsonrpc had some incompatible changes.

**Comment by titaniumbones** [comment]
I'll see if I can install it.  my config uses a bunch of emacs 29+ features though, so will be a bit slow testing. 

thanks for the heads up.

**Comment by lslarry86** [comment]
This is happening to me too.  I am brand new to copilot but 20+ year emacs user, so may be doing something wrong.  I am using emacs 28.2 for Windows on Windows 11 Pro, AMD 64 bit if it matters.  My jsonrpc is 1.0.14 and dash is 2.19.1, as specified. editorconfig is 2.19.1 and s.el is 1.13.1.  I see the same problems on copilot.el tip 0.9.8 (with nodejs 18.14.1) and a pre-proxy revision 0.9.6 from November 2022 (with nodejs 16.19.1 (x64). ).  The problem happens when running copilot-login or copilot-diagnose.

The Message "Copilot agent started." at the end of copilot--start-agent usually appears, followed within a second by the Message "or: Wrong type argument: number-or-marker-p, t".  The error seems to come from this line, right after the "agent started" message:
`(copilot--request 'initialize '(:capabilities 'nil))`

So far I've traced it to jsonrpc-connection-send but cannot tell yet which parameter is bad or how it gets that way.  If I then run pilot-diagnose I see a sentinel process error flash by, then "Sentinel for copilot agent still hasn't run, deleting it."  After that, emacs is frozen and has to be killed by the Task Manager.

I hope these details help.  I will keep trying with the older copilot version.  I'm at the limit of what I know about emacs and lisp now, so IDK if I will get much farther.

Thanks for doing this.

**Comment by lslarry86** [comment]
I'm wondering if the problem is not really a type error, but an error between emacs and nodejs that is not reported well on emacs.  Here are a couple of logfiles from sysinternals process monitor.  One shows just node.js, the other shows node and emacs.  The only thing notable to me is that node looks for a file called process.json and can't find it.  Emacs does not seem to create that file. Everything winds down after that failed file open.  Search for "process.json" or look at 10:35:24.3925550 AM in the Node only log, and 10:58:54.3231312 AM in the combined log.

[LogfileNodeOnly.CSV](https://github.com/zerolfx/copilot.el/files/10774692/LogfileNodeOnly.CSV)
[LogfileEmacsAndNode.CSV](https://github.com/zerolfx/copilot.el/files/10774693/LogfileEmacsAndNode.CSV)

**Comment by lslarry86** [comment]
Sorry if multiple posts violates etiquette or something.  I found the failure point, at least the first one:
`(defun jsonrpc--log-event (connection message &optional type)
  "Log a JSONRPC-related event.
CONNECTION is the current connection.  MESSAGE is a JSON-like
plist.  TYPE is a symbol saying if this is a client or server
originated."
  (let ((max (jsonrpc--events-buffer-scrollback-size connection)))
    (when (or (null max) (cl-plusp max))`
max evaluates to t (true), not any kind of size number, so cl-plusp objects to it.  These lines are the same in jsonrpc.el 1.0.14 and 1.0.16, so maybe copilot.el is doing something to trigger it, but only on some systems?
![error](https://user-images.githubusercontent.com/125607106/219882072-063cc5c0-9358-4405-8789-184d35d0f8b1.png)

**Comment by zerolfx** [comment]
@lslarry86 Thank you for figuring out the cause!!!

Could you try to tune this variable to see if it fixes the problem?

```elisp
(defcustom copilot-log-max message-log-max
  "Max size of events buffer. 0 disables, nil means infinite."
  :group 'copilot
  :type 'integer)
```

**Comment by lslarry86** [comment]
Good call.  I set copilot-log-max to 1000 and everything started working.  My emacs had message-log-max set to t (true) for no limit on log size.  That got copied to copilot-log-max and worked around to jsonrpc where it caused the problem.  That explains why it only affects some emacs builds.

**Comment by zerolfx** [comment]
Hmmm, for `jsonrpc--events-buffer-scrollback-size`, `nil` means infinite, but for `message-log-max`, `t` means infinite.

I will change the default value to 1000.
