### ISSUE TITLE
Disable globally / in buffer / in mode

### ISSUE THREAD

**Issue by MCSH** [zerolfx/copilot.el#8]
Hi!
Thank you for the great plugin, works flawlessly. I have one issue though, sometimes I want to disable the plugin and I don't know if there's an easy way to do it. For now, I've been commenting out the section that loads your plugin and restart emacs. I would like to see a functionality that does the following:

- Disable copilot globally (until resumed or restarted emacs)
- Disable copilot in this buffer
- Disable copilot in certain modes, such as org-mode.

Is there anything that allows me to do these already? Otherwise, can you either add them or point me towards the direction to implement them and possibly make a PR?

Thanks in advance!

**Comment by zerolfx** [comment]
Now in the `develop` branch, `copilot.el` acts as a minor mode (`copilot-mode`), so you can toggle it per buffer or hook it into other modes.

I haven't merged it because I used `evil-insert-state-p` in it, which aims at evil users only. I need to figure out how to config properly for vanilla Emacs users.

**Comment by nasyxx** [comment]
>  I need to figure out how to config properly for vanilla Emacs users.

Hi, for my Emacs config without the evil. 

I use copilot manually now since I feel it is noise when automatic appears.

```
(defun copilot---complete ()
  "Copilot complete."
  (interactive)
  (copilot-clear-overlay)
  (copilot-complete))

(add-hook 'post-command-hook #'copilot-clear-overlay)
```

Then, "H-SPC" for `copilot---complete,` manually start the copilot.  "C-<tab>" to accept.

The noise stands if we keep it open in some `major mode` that the copilot does not support.  We can have a list of functions that checks the current state if we can keep it working or not.  Like `rime-disable-predicates` in 

https://github.com/DogLooksGood/emacs-rime/blob/e5727c5218a4345adb9b960cf6f4202246aea70c/rime.el#L337-L342

https://github.com/DogLooksGood/emacs-rime/blob/e5727c5218a4345adb9b960cf6f4202246aea70c/rime.el#L105-L110

**Comment by zerolfx** [comment]
Thanks to @nasyxx 's suggestions!
I provided optional and customizable `copilot-mode` in the latest version.
