### ISSUE TITLE
Feature Request: LICENSE file

### ISSUE THREAD

**Issue by jgarte** [zerolfx/copilot.el#80]
Hi,

Are there any plans to add a LICENSE to this package?

I'd like to package it for GNU Guix and they require for everything to have a license.

**Comment by zerolfx** [comment]
I embed copyrighted files from [copilot.vim](https://github.com/github/copilot.vim) to make this plugin easy to install.

A possible solution:
+ Remove these copyrighted files from the repo.
+ Add a command to help users download these files.
+ Finally, add an open-source license (and submit this plugin to MELPA).

But I don't have the motivation to do so because it takes time and doesn't help the user experience.

**Comment by chrstfer** [comment]
Assuming we are somewhere like ~/.emacs.d/local/repos/copilot.el, we could always just do:

`git clone --depth=1 https://github.com/github/copilot.vim.git && cp -r copilot.vim/copilot/dist/ && rm -r copilot.vim` 

In some elisp function. Then you can have your license and a copilot too!

**Comment by zerolfx** [comment]
@chrstfer 

Thanks for your suggestion. Yes, it's feasible, but I won't prioritize it.
By the way, It is also necessary to check the current version of the dist folder and fetch a specific version from copilot.vim if not compatible.

**Comment by chrstfer** [comment]
Agreed, not a huge deal at the moment. I was just outlining what might be done since it looked like there was a question of what path to go forward. Ideally limited user interaction to do so, so I figured something within elisp would be ideal.
